### ISSUE TITLE
M3u8 url not working

### ISSUE THREAD

**Issue by DecosSoft** [Greyh4t/m3u8-Downloader#5]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 96, in <module>
  File "<string>", line 39, in run
TypeError: a bytes-like object is required, not 'str'

**Comment by Greyh4t** [comment]
This error seems to be an error of the environment itself, and I cannot solve it. In addition, the script has only been tested under python2
